### ISSUE TITLE
"README" required but "README.md" is available

### ISSUE THREAD

**Issue by wkazubski** [Opendigitalradio/qt-drmplus#3]
When trying to build qt-dablus I get this:
...
./autogen.sh --prefix=/usr
Generating configuration files for libdrmplus, please wait....
  aclocal 
aclocal: warning: couldn't open directory 'm4': No such file or directory
  autoheader
  libtoolize --automake
  automake --add-missing 
configure.ac:11: installing './compile'
configure.ac:17: installing './config.guess'
configure.ac:17: installing './config.sub'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
Makefile.am: installing './INSTALL'
Makefile.am: error: required file './README' not found
frontend/Makefile.am: installing './depcomp'
  autoreconf
Makefile.am: error: required file './README' not found
autoreconf: automake failed with exit status: 1
...
and Makefile.in, required for ./configure is not created.

**Comment by mpbraendli** [comment]
@piratfm, use `AM_INIT_AUTOMAKE([foreign])` in your `configure.ac` to avoid this issue.

See https://autotools.io/automake/options.html for an explanation.

**Comment by mpbraendli** [comment]
And maybe also make sure it doesn't take the very old tar format as default: 

`AM_INIT_AUTOMAKE([tar-ustar foreign])`

https://www.gnu.org/software/automake/manual/html_node/List-of-Automake-options.html#List-of-Automake-options

**Comment by piratfm** [comment]
Fixed
